# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'GiphySearch' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GiphySearch
  pod 'RxSwift',    '~> 2.0'
  pod 'RxCocoa',    '~> 2.0'
  pod 'Moya/RxSwift'
  pod 'NSObject+Rx'
  pod 'ObjectMapper'
  pod 'Moya-ObjectMapper/RxSwift'
  pod 'RxAlamofire'
  pod 'SDWebImage/GIF', git: 'https://github.com/rs/SDWebImage.git', branch: '4.x'
  pod 'SnapKit', '0.19.1'

  target 'GiphySearchTests' do
    inherit! :search_paths
    # Pods for testing

    pod 'Quick', '0.9.1'
    pod 'Nimble', '3.2.0'
  end

end
