# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target 'GiphySearch' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GiphySearch
  pod 'RxSwift',    '3.0.1'
  pod 'RxCocoa',    '3.0.1'
  pod 'Moya/RxSwift', '8.0.0-beta.4'
  pod 'NSObject+Rx', '2.0.0'
  pod 'ObjectMapper'
  pod 'Moya-ObjectMapper/RxSwift', '2.2.1'
  pod 'RxAlamofire', '3.0.2'
  pod 'Kingfisher', '3.1.4'
  pod 'SnapKit', '3.1.2'

  target 'GiphySearchTests' do
    inherit! :search_paths
    # Pods for testing

    pod 'Quick', '~> 1'
    pod 'Nimble', '~> 5.1'
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
          config.build_settings['SWIFT_VERSION'] = '3.0'
      end
  end
end
